### ISSUE TITLE
DefinitelyTyped entry for classical.js

### ISSUE THREAD

**Issue by jordankid93** [drubino/Classical#2]
Trying to find an entry for classical.js in Typings and nothing is coming up. Obvi I could just save and drag the file in by itself but being able to just do "typings install" would be easier for my team and would allow newcomers to get started a bit quicker. Thanks :)

**Comment by drubino** [comment]
@jordankid93 Thanks for your interest in classical.js! Unfortunately the project is no longer being actively developed. If you work in a .Net environment, classical.js is distributed via nuget: https://www.nuget.org/packages/Classical. Alternatively, you should feel free to add the type definitions to DefinitelyTypes if that would be useful to your team.

**Comment by jordankid93** [comment]
Awesome, that's great. I will look into getting it on DT. Thanks!
